/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

import static apotek.GudangIndexFrame.date;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import apotek.ObatIndexFrame;
import static apotek.PengirimanIndexFrame.con;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListModel;
import javax.swing.DefaultListModel;
import java.util.ListResourceBundle;

/**
 *
 * @author BAYU
 */
public class PengirimanCreateFrame extends javax.swing.JFrame {

    static Connection con;
    static Statement statement;
    static ResultSet result;
    static java.util.Date date = new java.util.Date();

    //Add To Gudang
    static ResultSet gudang_result;

    //Obat Statement and ResultSet
    static Statement obat_statement;
    static ResultSet data_obat;
    //Agen Statement and ResultSet
    static Statement agen_statement;
    static ResultSet data_agen;
    //Apoteker Statement and ResultSet
    static Statement apoteker_statement;
    static ResultSet data_apoteker;

    /**
     * Creates new form dashboardFrame
     */
    public PengirimanCreateFrame() {
        initComponents();
        setDefaultData();
    }

    private void setDefaultData() {
        try {
            DefaultListModel<String> obat_model = new DefaultListModel<>();
            DefaultListModel<String> agen_model = new DefaultListModel<>();
            DefaultListModel<String> apoteker_model = new DefaultListModel<>();
            con = DriverManager.getConnection("jdbc:mysql://localhost/apotek", "root", "");
            // Fetch All Obat Data From Table obat
            obat_statement = con.createStatement();
            data_obat = obat_statement.executeQuery("SELECT * FROM obat ORDER BY obat.nama_obat ASC");
            // Fetch All Agen Data From Table agen
            agen_statement = con.createStatement();
            data_agen = agen_statement.executeQuery("SELECT * FROM agen ORDER BY agen.nama ASC");
            // Fetch All Apoteker Data From Table apoteker
            apoteker_statement = con.createStatement();
            data_apoteker = apoteker_statement.executeQuery("SELECT * FROM apoteker ORDER BY `apoteker`.`nama` ASC");
            while (data_obat.next()) {
                obat_model.addElement(data_obat.getString("id_obat") + " - " + data_obat.getString("nama_obat"));
            }
            while (data_agen.next()) {
                agen_model.addElement(data_agen.getString("id_agen") + " - " + data_agen.getString("nama"));
            }
            while (data_apoteker.next()) {
                apoteker_model.addElement(data_apoteker.getString("id_apoteker") + " - " + data_apoteker.getString("nama"));
            }
            //Adding to List
            obat_list.setModel(obat_model);
            agen_list.setModel(agen_model);
            apoteker_list.setModel(apoteker_model);

            //Give tanggal_pengiriman_textbox a default value
            String todayDate = (date.getYear() + 1900) + "-" + (date.getMonth() + 1) + "-" + date.getDate();
            tanggal_pengiriman_textbox.setText(todayDate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection error : " + e);
        }
    }

    private void clearAll() {
//        name_textbox.setText("");
//        merk_textbox.setText("");
//        dosis_spinner.setValue(0);
//        composition_textarea.setText("");
//        harga_spinner.setValue(0);
    }

    private void clearValidation() {
        obat_invalid_text.setText(" ");
        agen_invalid_text.setText(" ");
        apoteker_invalid_text.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        agen_invalid_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        apoteker_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        agen_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        obat_list = new javax.swing.JList<>();
        total_obat_spinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tanggal_pengiriman_textbox = new javax.swing.JTextField();
        ubah_tanggal_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apoteker_invalid_text = new javax.swing.JLabel();
        obat_invalid_text = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(170, 172, 173));
        jPanel2.setForeground(new java.awt.Color(139, 139, 139));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton1.setText("Apoteker");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel1.setText("Manajemen Pengiriman Obat");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel2.setText("Tambah Data Pengiriman");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel3.setText("Total Obat : ");

        submit_btn.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        submit_btn.setText("Tambah");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        back_btn.setText("Kembali");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        agen_invalid_text.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        agen_invalid_text.setForeground(new java.awt.Color(243, 36, 36));
        agen_invalid_text.setText("                                           ");

        apoteker_list.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jScrollPane1.setViewportView(apoteker_list);

        agen_list.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        agen_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(agen_list);

        obat_list.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        obat_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(obat_list);

        total_obat_spinner.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel4.setText("Tanggal Pengiriman : ");

        tanggal_pengiriman_textbox.setEditable(false);
        tanggal_pengiriman_textbox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        tanggal_pengiriman_textbox.setText("2019-11-13");

        ubah_tanggal_btn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ubah_tanggal_btn.setText("Ubah Tanggal");
        ubah_tanggal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_tanggal_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("Pilih Agen Pengirim : ");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setText("Pilih Apoteker Penerima : ");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setText("Pilih Obat Yang Dikirim : ");

        apoteker_invalid_text.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        apoteker_invalid_text.setForeground(new java.awt.Color(243, 36, 36));
        apoteker_invalid_text.setText("                                           ");

        obat_invalid_text.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        obat_invalid_text.setForeground(new java.awt.Color(243, 36, 36));
        obat_invalid_text.setText("                                           ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 552, Short.MAX_VALUE)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(agen_invalid_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(apoteker_invalid_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(obat_invalid_text, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tanggal_pengiriman_textbox))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(total_obat_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ubah_tanggal_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(back_btn))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agen_invalid_text)
                    .addComponent(apoteker_invalid_text)
                    .addComponent(obat_invalid_text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total_obat_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tanggal_pengiriman_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubah_tanggal_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(submit_btn)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // Validation
        if (agen_list.getSelectedValue().equals(null)) {
            agen_invalid_text.setText("Agen wajib dipilih!");
        } else if (apoteker_list.getSelectedValue().equals(null)) {
            apoteker_invalid_text.setText("Apoteker Wajib dipilih!");
        } else if (obat_list.getSelectedValue().equals(null)) {
            obat_invalid_text.setText("Obat Wajib dipilih!");
        } else {
            this.clearValidation();
            String id_apoteker = apoteker_list.getSelectedValue().split(" - ", 2)[0];
            String id_agen = agen_list.getSelectedValue().split(" - ", 2)[0];
            String id_obat = obat_list.getSelectedValue().split(" - ", 2)[0];
            int total_obat = Integer.valueOf(String.valueOf(total_obat_spinner.getValue()));
            String tanggal_pengiriman = tanggal_pengiriman_textbox.getText();
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/apotek", "root", "");
                statement = con.createStatement();
                statement.executeUpdate("INSERT INTO `pengiriman_obat` (`id_pengiriman`, `id_agen`, `id_apoteker`, `tanggal_pengiriman`, `id_obat`, `total_obat`) VALUES (NULL, '" + id_agen + "', '" + id_apoteker + "', '" + tanggal_pengiriman + "', '" + id_obat + "', '" + total_obat + "');");
                String today_date = (date.getYear() + 1900) + "-" + (date.getMonth() + 1) + "-" + date.getDate();
                try {
                    gudang_result = statement.executeQuery("SELECT * FROM gudang WHERE id_obat = '" + id_obat + "'");
                    if (gudang_result.next()) {
                        int updated_stock = total_obat + Integer.valueOf(gudang_result.getString("stock"));
                        statement.executeUpdate("UPDATE `gudang` SET `stock` = '" + updated_stock + "', `penambahan_terakhir` = '" + today_date + "' WHERE `gudang`.`id_penyimpanan` = " + Integer.valueOf(gudang_result.getString("id_penyimpanan")) + ";"
                        );
                        clearAll();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Connection error" + e);
                }
                JOptionPane.showMessageDialog(null, "Pengiriman berhasil ditambahkan");
                clearAll();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Connection error" + e);
            }
        }

    }//GEN-LAST:event_submit_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        new ObatIndexFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void ubah_tanggal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_tanggal_btnActionPerformed
        // TODO add your handling code here:
        tanggal_pengiriman_textbox.setEditable(true);
    }//GEN-LAST:event_ubah_tanggal_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PengirimanCreateFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agen_invalid_text;
    private javax.swing.JList<String> agen_list;
    private javax.swing.JLabel apoteker_invalid_text;
    private javax.swing.JList<String> apoteker_list;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel obat_invalid_text;
    private javax.swing.JList<String> obat_list;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField tanggal_pengiriman_textbox;
    private javax.swing.JSpinner total_obat_spinner;
    private javax.swing.JButton ubah_tanggal_btn;
    // End of variables declaration//GEN-END:variables
}
