/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import apotek.ObatIndexFrame;
import javax.swing.DefaultListModel;

/**
 *
 * @author BAYU
 */
public class PenjualanCreateFrame extends javax.swing.JFrame {

    static Connection con;
    static Statement statement;
    static ResultSet result;
    static java.util.Date date = new java.util.Date();

    //Add To Gudang
    static ResultSet gudang_result;

    //Obat Statement and ResultSet
    static Statement obat_statement;
    static ResultSet data_obat;
    //Agen Statement and ResultSet
    static Statement pembeli_statement;
    static ResultSet data_pembeli;
    //Apoteker Statement and ResultSet
    static Statement apoteker_statement;
    static ResultSet data_apoteker;

    /**
     * Creates new form dashboardFrame
     */
    public PenjualanCreateFrame() {
        initComponents();
        setDefaultData();
    }

    private void setDefaultData() {
        try {
            DefaultListModel<String> obat_model = new DefaultListModel<>();
            DefaultListModel<String> pembeli_model = new DefaultListModel<>();
            DefaultListModel<String> apoteker_model = new DefaultListModel<>();
            con = DriverManager.getConnection("jdbc:mysql://localhost/apotek", "root", "");
            // Fetch All Obat Data From Table obat
            obat_statement = con.createStatement();
            data_obat = obat_statement.executeQuery("SELECT * FROM obat ORDER BY obat.nama_obat ASC");
            // Fetch All Agen Data From Table agen
            pembeli_statement = con.createStatement();
            data_pembeli = pembeli_statement.executeQuery("SELECT * FROM pembeli ORDER BY pembeli.nama ASC");
            // Fetch All Apoteker Data From Table apoteker
            apoteker_statement = con.createStatement();
            data_apoteker = apoteker_statement.executeQuery("SELECT * FROM apoteker ORDER BY `apoteker`.`nama` ASC");
            while (data_obat.next()) {
                obat_model.addElement(data_obat.getString("id_obat") + " - " + data_obat.getString("nama_obat"));
            }
            while (data_pembeli.next()) {
                pembeli_model.addElement(data_pembeli.getString("id_pembeli") + " - " + data_pembeli.getString("nama"));
            }
            while (data_apoteker.next()) {
                apoteker_model.addElement(data_apoteker.getString("id_apoteker") + " - " + data_apoteker.getString("nama"));
            }
            //Adding to List
            obat_list.setModel(obat_model);
            pembeli_list.setModel(pembeli_model);
            apoteker_list.setModel(apoteker_model);

            //Give tanggal_pengiriman_textbox a default value
            String todayDate = (date.getYear() + 1900) + "-" + (date.getMonth() + 1) + "-" + date.getDate();
            tanggal_pembelian_textbox.setText(todayDate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection error : " + e);
        }
    }

    private void clearValidation() {
        obat_invalid_text.setText(" ");
        pembeli_invalid_text.setText(" ");
        apoteker_invalid_text.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        pembeli_invalid_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        apoteker_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        pembeli_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        obat_list = new javax.swing.JList<>();
        total_obat_spinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tanggal_pembelian_textbox = new javax.swing.JTextField();
        ubah_tanggal_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apoteker_invalid_text = new javax.swing.JLabel();
        obat_invalid_text = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keterangan_textbox = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(170, 172, 173));
        jPanel2.setForeground(new java.awt.Color(139, 139, 139));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jButton1.setText("Apoteker");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel1.setText("Manajemen Penjualan Obat");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        jLabel2.setText("Tambah Data Penjualan");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel3.setText("Total Obat : ");

        submit_btn.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        submit_btn.setText("Tambah");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        back_btn.setText("Kembali");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        pembeli_invalid_text.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        pembeli_invalid_text.setForeground(new java.awt.Color(243, 36, 36));
        pembeli_invalid_text.setText("                                           ");

        apoteker_list.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        apoteker_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(apoteker_list);

        pembeli_list.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        pembeli_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(pembeli_list);

        obat_list.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        obat_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(obat_list);

        total_obat_spinner.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel4.setText("Tanggal Pembelian : ");

        tanggal_pembelian_textbox.setEditable(false);
        tanggal_pembelian_textbox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        tanggal_pembelian_textbox.setText("2019-11-13");

        ubah_tanggal_btn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ubah_tanggal_btn.setText("Ubah Tanggal");
        ubah_tanggal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_tanggal_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("Pilih Pembeli : ");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setText("Pilih Apoteker Penjual : ");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setText("Pilih Obat Yang Dibeli : ");

        apoteker_invalid_text.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        apoteker_invalid_text.setForeground(new java.awt.Color(243, 36, 36));
        apoteker_invalid_text.setText("                                           ");

        obat_invalid_text.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        obat_invalid_text.setForeground(new java.awt.Color(243, 36, 36));
        obat_invalid_text.setText("                                           ");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel8.setText("Keterangan : ");

        keterangan_textbox.setColumns(20);
        keterangan_textbox.setRows(5);
        jScrollPane2.setViewportView(keterangan_textbox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(582, 582, 582)
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(total_obat_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggal_pembelian_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ubah_tanggal_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel5)
                            .addComponent(pembeli_invalid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel6)
                            .addComponent(apoteker_invalid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obat_invalid_text, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(back_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembeli_invalid_text)
                    .addComponent(apoteker_invalid_text)
                    .addComponent(obat_invalid_text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total_obat_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tanggal_pembelian_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubah_tanggal_btn))
                .addGap(22, 22, 22)
                .addComponent(submit_btn)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // Validation
        if (pembeli_list.getSelectedValue() == null) {
            pembeli_invalid_text.setText("Agen wajib dipilih!");
        } else if (apoteker_list.getSelectedValue() == null) {
            apoteker_invalid_text.setText("Apoteker Wajib dipilih!");
        } else if (obat_list.getSelectedValue() == null) {
            obat_invalid_text.setText("Obat Wajib dipilih!");
        } else {
            this.clearValidation();
            String id_apoteker = apoteker_list.getSelectedValue().split(" - ", 2)[0];
            String id_pembeli = pembeli_list.getSelectedValue().split(" - ", 2)[0];
            String id_obat = obat_list.getSelectedValue().split(" - ", 2)[0];
            String keterangan;
            if (keterangan_textbox.getText().equals("")) {
                keterangan = "Tidak ada keterangan";
            } else {
                keterangan = keterangan_textbox.getText();
            }

            int total_obat = Integer.valueOf(String.valueOf(total_obat_spinner.getValue()));
            String tanggal_pembelian = tanggal_pembelian_textbox.getText();
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/apotek", "root", "");
                statement = con.createStatement();
                statement.executeUpdate("INSERT INTO `penjualan_obat` (`id_penjualan`, `id_pembeli`, `id_apoteker`, `id_obat`, `total_obat`, `keterangan`, `tanggal_pembelian`) VALUES (NULL, '" + id_pembeli + "', '" + id_apoteker + "', '" + id_obat + "', '" + total_obat + "', '" + keterangan + "', '" + tanggal_pembelian + "');");
                String today_date = (date.getYear() + 1900) + "-" + (date.getMonth() + 1) + "-" + date.getDate();
                try {
                    gudang_result = statement.executeQuery("SELECT * FROM gudang WHERE id_obat = '" + id_obat + "'");
                    if (gudang_result.next()) {
                        int updated_stock = Integer.valueOf(gudang_result.getString("stock")) - total_obat;
                        statement.executeUpdate("UPDATE `gudang` SET `stock` = '" + updated_stock + "', `pengambilan_terakhir` = '" + today_date + "' WHERE `gudang`.`id_penyimpanan` = " + Integer.valueOf(gudang_result.getString("id_penyimpanan")) + ";"
                        );
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Connection error" + e);
                }
                JOptionPane.showMessageDialog(null, "Data penjualan berhasil ditambahkan");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Connection error" + e);
            }
        }

    }//GEN-LAST:event_submit_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        new ObatIndexFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void ubah_tanggal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_tanggal_btnActionPerformed
        // TODO add your handling code here:
        tanggal_pembelian_textbox.setEditable(true);
    }//GEN-LAST:event_ubah_tanggal_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PenjualanCreateFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apoteker_invalid_text;
    private javax.swing.JList<String> apoteker_list;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea keterangan_textbox;
    private javax.swing.JLabel obat_invalid_text;
    private javax.swing.JList<String> obat_list;
    private javax.swing.JLabel pembeli_invalid_text;
    private javax.swing.JList<String> pembeli_list;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField tanggal_pembelian_textbox;
    private javax.swing.JSpinner total_obat_spinner;
    private javax.swing.JButton ubah_tanggal_btn;
    // End of variables declaration//GEN-END:variables
}
